[server]
hostname = "localhost"
node_ip = "127.0.0.1"
offset=4
server_role="api-devportal"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/SHARED_DB_WSO2AM_320?useSSL=false"
username = "MYSQL_ROOT_USERNAME"
password = "MYSQL_ROOT_PASSWORD"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/APIM_DB_WSO2AM_320?useSSL=false"
username = "MYSQL_ROOT_USERNAME"
password = "MYSQL_ROOT_PASSWORD"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://localhost:9445/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://localhost:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint= "ws://localhost:9099"
http_endpoint = "http://localhost:8280"
https_endpoint = "https://localhost:8243"
show_as_token_endpoint_url = true

[apim.cache.recent_apis]
enable = false

[apim.cache.scopes]
enable = true

[apim.cache.tags]
expiry_time = 120000

[apim.devportal]
enable_application_sharing = true
application_sharing_type = "default" #changed to type, saml, default
#application_sharing_impl = "org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl"
display_multiple_versions = false
display_deprecated_apis = false
enable_comments = true
enable_ratings = true
enable_forum = true

[[event_handler]]
name="userPostSelfRegistration"
subscriptions=["POST_ADD_USER"]

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
throttle_decision_endpoints = ["tcp://localhost:5673"]

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://localhost:9612"]
traffic_manager_auth_urls=["ssl://localhost:9712"]