[server]
hostname = "localhost"
node_ip = "127.0.0.1"
offset=1
server_role = "traffic-manager"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/SHARED_DB_WSO2AM_320?useSSL=false"
username = "MYSQL_ROOT_USERNAME"
password = "MYSQL_ROOT_PASSWORD"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/APIM_DB_WSO2AM_320?useSSL=false"
username = "MYSQL_ROOT_USERNAME"
password = "MYSQL_ROOT_PASSWORD"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://localhost:9445/services/"

[apim.oauth_config]
revoke_endpoint = "https://localhost:9445/oauth2/revoke"
enable_token_encryption = false
enable_token_hashing = false